### ISSUE TITLE
Incorrect Amount Format

### ISSUE THREAD

**Issue by solaris007** [damoiser/qr-bills#17]
The amount is formatted "...xxx.x" instead of "...xxx.xx", suggest using `'%.2f'` for amount outputs in the HTML layout.

**Comment by solaris007** [comment]
PR: https://github.com/damoiser/qr-bills/pull/18

**Comment by solaris007** [comment]
fixed via #18 and v1.0.5

**Comment by solaris007** [comment]
@damoiser i think we were both a bit tired yesterday :) We forgot to format the value *in the QR payload* and we put the EC level on the PNG method instead of the QR constructor.

https://github.com/damoiser/qr-bills/pull/19

**Comment by damoiser** [comment]
yes @solaris007 :-) 

thanks again for the PR and the fix, just merged and published the new version to rubygems repository. I will then close this issue.
