### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by danielpuglisi** [damoiser/qr-bills#22]
Hey @damoiser 

I implemented a working SVG format option: https://github.com/codegestalt/qr-bills/commit/c0b4e5e609925841cf5bc0c6f98d9bf7b5044acc

Any interest in adopting this? I removed the PNG format in my fork, as I don't see the use case for png support with the svg format option present. But I can put together a PR with both options available if needed.

**Comment by damoiser** [comment]
Hi @danielpuglisi, thanks for the enhancement proposal, please keep the PNG as backward compatibility, seen that some applications may already use that. PNG should be the default one but with a config the application would be able to select SVG. 

Thanks!

**Comment by danielpuglisi** [comment]
Alright, will do that and open a PR 👍

**Comment by damoiser** [comment]
new version released v1.0.8! thx for the PR!
